/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_js_SCARlib_SCARLib */

#ifndef _Included_edu_js_SCARlib_SCARLib
#define _Included_edu_js_SCARlib_SCARLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_js_SCARlib_SCARLib
 * Method:    XOpenDisplay
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_edu_js_SCARlib_SCARLib_XOpenDisplay__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     edu_js_SCARlib_SCARLib
 * Method:    XOpenDisplay
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_edu_js_SCARlib_SCARLib_XOpenDisplay__
  (JNIEnv *, jobject);

/*
 * Class:     edu_js_SCARlib_SCARLib
 * Method:    UserFindWindow
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_edu_js_SCARlib_SCARLib_UserFindWindow
  (JNIEnv *, jobject, jlong);

/*
 * Class:     edu_js_SCARlib_SCARLib
 * Method:    XCloseDisplay
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_edu_js_SCARlib_SCARLib_XCloseDisplay
  (JNIEnv *, jobject, jlong);

/*
 * Class:     edu_js_SCARlib_SCARLib
 * Method:    getWindowLocation
 * Signature: (JJ)Ljava/awt/Point;
 */
JNIEXPORT jobject JNICALL Java_edu_js_SCARlib_SCARLib_getWindowLocation
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     edu_js_SCARlib_SCARLib
 * Method:    getWindowByName
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_edu_js_SCARlib_SCARLib_getWindowByName
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     edu_js_SCARlib_SCARLib
 * Method:    getRootWindow
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_edu_js_SCARlib_SCARLib_getRootWindow
  (JNIEnv *, jobject, jlong);

/*
 * Class:     edu_js_SCARlib_SCARLib
 * Method:    ActivateWindow
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_edu_js_SCARlib_SCARLib_ActivateWindow
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     edu_js_SCARlib_SCARLib
 * Method:    GetWindowDimensions
 * Signature: (JJ)Ljava/awt/Point;
 */
JNIEXPORT jobject JNICALL Java_edu_js_SCARlib_SCARLib_GetWindowDimensions
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     edu_js_SCARlib_SCARLib
 * Method:    getWindowByNamePart
 * Signature: (JLjava/lang/String;Z)J
 */
JNIEXPORT jlong JNICALL Java_edu_js_SCARlib_SCARLib_getWindowByNamePart
  (JNIEnv *, jobject, jlong, jstring, jboolean);

/*
 * Class:     edu_js_SCARlib_SCARLib
 * Method:    GetWindowBySize
 * Signature: (JII)J
 */
JNIEXPORT jlong JNICALL Java_edu_js_SCARlib_SCARLib_GetWindowBySize
  (JNIEnv *, jobject, jlong, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
